
import { GoogleGenAI, Type } from "@google/genai";
import { AiSearchResult } from '../types';

// IMPORTANT: This key is managed externally by the execution environment.
// Do not hardcode or manage it in the UI.
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might want to handle this more gracefully,
  // but for this example, we'll throw an error if the key is missing.
  console.warn("API_KEY environment variable not set. Gemini features will not work.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

const responseSchema = {
    type: Type.OBJECT,
    properties: {
        summary: {
            type: Type.STRING,
            description: "A short, helpful summary of the search query in 1-3 sentences. If the query is about 'Roblox', prioritize official sources in the summary."
        },
        sites: {
            type: Type.ARRAY,
            description: "A list of 3 to 6 relevant website suggestions.",
            items: {
                type: Type.OBJECT,
                properties: {
                    title: { type: Type.STRING, description: "The title of the website." },
                    url: { type: Type.STRING, description: "The full URL of the website." },
                    summary: { type: Type.STRING, description: "A 2-sentence summary of the website's content, generated by the AI." },
                    safety: { type: Type.STRING, description: "A safety rating: 'Güvenli', 'İzleniyor', or 'Potansiyel Risk'." },
                },
                required: ["title", "url", "summary", "safety"],
            }
        }
    },
    required: ["summary", "sites"],
};


export const getAiSearchResults = async (query: string): Promise<AiSearchResult | null> => {
    if (!API_KEY) return null;

    try {
        const prompt = `User searched for: "${query}". 
        Provide a 1-3 sentence summary. 
        Then, list 3 to 6 relevant and safe websites for this query. 
        For each website, provide a title, a full URL, a 2-sentence summary, and a safety rating ('Güvenli', 'İzleniyor', 'Potansiyel Risk').
        Prioritize official sources if the query is about a specific brand like "Roblox".
        Format the response as the requested JSON object.`;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: responseSchema,
            },
        });
        
        const jsonText = response.text.trim();
        const result = JSON.parse(jsonText);
        return result as AiSearchResult;

    } catch (error) {
        console.error("Error fetching AI search results:", error);
        return null;
    }
};
